id = "zed-legacy-themes"
name = "Zed Legacy Themes"
version = "0.0.1"
schema_version = 1
authors = ["Nate Butler <iamnbutler@gmail.com>"]
description = "Some of the legacy themes Zed shipped with initially: Andromeda, Atelier, Ros√© Pine, Sandcastle, Solarized, Summercamp"
repository = "https://github.com/zed-extensions/legacy-themes"
